[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

; Reserves 1MB for the LittleFS partition where fpga.bin lives [cite: 2026-02-14]
board_build.filesystem = littlefs
board_build.filesystem_size = 1m

monitor_speed = 115200

lib_deps = 
    https://github.com/vicharak-in/shrike_arduino.git